### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by CitroenGames** [rfsheffer/RyansUE4Helpers#1]
![image](https://user-images.githubusercontent.com/54474809/209725338-b1b66c8e-e2fc-43f1-94d4-8eab2ea18989.png)

**Comment by CitroenGames** [comment]
this is the error i recieve when i export my project

**Comment by rfsheffer** [comment]
Hi there!

I will add the include:
#include "Runtime/Engine/Public/LatentActions.h"
To this code files header includes which should resolve this.

Which engine version are you targeting? 4.27 and beyond have been compiled within Epic's toolchain and my own so it is interesting this error has shown up. Rider seemed to think there weren't any missing declarations as well... However, considering the seemingly random nature of the code unit consolidation, I am not surprised these errors show up from time to time.

Cheers!

**Comment by CitroenGames** [comment]
hi, 

i am targeting source version of ue5.1 i havent made changes to the engine i needed it for features that normal ue5.1 doesnt have.
i will try to include that to the header file and see if it resolves it.

**Comment by CitroenGames** [comment]
oh i just realized that you already added that.
i just compiled and it works!
![image](https://user-images.githubusercontent.com/54474809/209777230-9808630f-84e0-4fe2-aa7c-43ec53c2ffbe.png)

**Comment by rfsheffer** [comment]
Thanks for the report :)
